---
- name: Copy config
  template:
    src: "{{path_config}}"
    dest: /etc/nginx/nginx.conf
  tags: "{{tag}}"

- name: Check nginx config file
  shell: "{{application}} -t"

- name: Restart nginx
  service:
    name: "{{application}}"
    state: restarted
