pipeline {
    agent {
        label 'master'
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("ansible ping host") {
            steps {
                echo " ============== ping nginx host =================="
                withCredentials([usernamePassword(credentialsId: 'ansible_creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                   sh("""
                        ansible -m ping -i ./hosts/production nginx -e "ansible_user=root ansible_password=$PASSWORD; echo"
                    """)
                }
            }
        }
        stage('ansible run playbook') { 
            steps {
               echo " ============== Ansible playbook run =================="
                ansiblePlaybook(
                    vaultCredentialsId: 'AnsibleVault',
                    inventory: './hosts/production',
                    playbook: 'main.yml'
                )
            }
        }
    }
}
